"""Add is_active column to jobs table

Revision ID: 7227829a0ec0
Revises: d3f665042a3e
Create Date: 2024-12-17 10:35:39.309063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7227829a0ec0'
down_revision: Union[str, None] = 'd3f665042a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'applications', ['uid'])
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'jobs', ['uid'])
    op.create_unique_constraint(None, 'users', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_column('jobs', 'is_active')
    op.drop_constraint(None, 'applications', type_='unique')
    # ### end Alembic commands ###
